# **Cross-validation & Grid-search**

---
## Imports

In [1]:
# cross val & grid-search
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV

# modèles
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.neural_network import MLPClassifier

# python lib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
import time

In [2]:
# lib pour importer le dataset
from ucimlrepo import fetch_ucirepo
# fetch dataset
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17) 
# data (as pandas dataframes) 
X = breast_cancer_wisconsin_diagnostic.data.features 
y = breast_cancer_wisconsin_diagnostic.data.targets

---
## Informations sur le dataset

In [3]:
breast_cancer_wisconsin_diagnostic.metadata

{'uci_id': 17,
 'name': 'Breast Cancer Wisconsin (Diagnostic)',
 'repository_url': 'https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic',
 'data_url': 'https://archive.ics.uci.edu/static/public/17/data.csv',
 'abstract': 'Diagnostic Wisconsin Breast Cancer Database.',
 'area': 'Health and Medicine',
 'tasks': ['Classification'],
 'characteristics': ['Multivariate'],
 'num_instances': 569,
 'num_features': 30,
 'feature_types': ['Real'],
 'demographics': [],
 'target_col': ['Diagnosis'],
 'index_col': ['ID'],
 'has_missing_values': 'no',
 'missing_values_symbol': None,
 'year_of_dataset_creation': 1993,
 'last_updated': 'Fri Nov 03 2023',
 'dataset_doi': '10.24432/C5DW2B',
 'creators': ['William Wolberg',
  'Olvi Mangasarian',
  'Nick Street',
  'W. Street'],
 'intro_paper': {'ID': 230,
  'type': 'NATIVE',
  'title': 'Nuclear feature extraction for breast tumor diagnosis',
  'authors': 'W. Street, W. Wolberg, O. Mangasarian',
  'venue': 'Electronic imaging',
  'year': 1993,
  'journal': None,
  'DOI': '10.1117/12.148698',
  'URL': 'https://www.semanticscholar.org/paper/53f0fbb425bc14468eb3bf96b2e1d41ba8087f36',
  'sha': None,
  'corpus': None,
  'arxiv': None,
  'mag': None,
  'acl': None,
  'pmid': None,
  'pmcid': None},
 'additional_info': {'summary': 'Features are computed from a digitized image of a fine needle aspirate (FNA) of a breast mass.  They describe characteristics of the cell nuclei present in the image. A few of the images can be found at http://www.cs.wisc.edu/~street/images/\r\n\r\nSeparating plane described above was obtained using Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree Construction Via Linear Programming." Proceedings of the 4th Midwest Artificial Intelligence and Cognitive Science Society, pp. 97-101, 1992], a classification method which uses linear programming to construct a decision tree.  Relevant features were selected using an exhaustive search in the space of 1-4 features and 1-3 separating planes.\r\n\r\nThe actual linear program used to obtain the separating plane in the 3-dimensional space is that described in: [K. P. Bennett and O. L. Mangasarian: "Robust Linear Programming Discrimination of Two Linearly Inseparable Sets", Optimization Methods and Software 1, 1992, 23-34].\r\n\r\nThis database is also available through the UW CS ftp server:\r\nftp ftp.cs.wisc.edu\r\ncd math-prog/cpo-dataset/machine-learn/WDBC/',
  'purpose': None,
  'funded_by': None,
  'instances_represent': None,
  'recommended_data_splits': None,
  'sensitive_data': None,
  'preprocessing_description': None,
  'variable_info': '1) ID number\r\n2) Diagnosis (M = malignant, B = benign)\r\n3-32)\r\n\r\nTen real-valued features are computed for each cell nucleus:\r\n\r\n\ta) radius (mean of distances from center to points on the perimeter)\r\n\tb) texture (standard deviation of gray-scale values)\r\n\tc) perimeter\r\n\td) area\r\n\te) smoothness (local variation in radius lengths)\r\n\tf) compactness (perimeter^2 / area - 1.0)\r\n\tg) concavity (severity of concave portions of the contour)\r\n\th) concave points (number of concave portions of the contour)\r\n\ti) symmetry \r\n\tj) fractal dimension ("coastline approximation" - 1)',
  'citation': None}}

In [4]:
print(breast_cancer_wisconsin_diagnostic.variables)

                  name     role         type demographic description units  \
0                   ID       ID  Categorical        None        None  None
1            Diagnosis   Target  Categorical        None        None  None
2              radius1  Feature   Continuous        None        None  None
3             texture1  Feature   Continuous        None        None  None
4           perimeter1  Feature   Continuous        None        None  None
5                area1  Feature   Continuous        None        None  None
6          smoothness1  Feature   Continuous        None        None  None
7         compactness1  Feature   Continuous        None        None  None
8           concavity1  Feature   Continuous        None        None  None
9      concave_points1  Feature   Continuous        None        None  None
10           symmetry1  Feature   Continuous        None        None  None
11  fractal_dimension1  Feature   Continuous        None        None  None
12             radius2  Feature   Continuous        None        None  None
13            texture2  Feature   Continuous        None        None  None
14          perimeter2  Feature   Continuous        None        None  None
15               area2  Feature   Continuous        None        None  None
16         smoothness2  Feature   Continuous        None        None  None
17        compactness2  Feature   Continuous        None        None  None
18          concavity2  Feature   Continuous        None        None  None
19     concave_points2  Feature   Continuous        None        None  None
20           symmetry2  Feature   Continuous        None        None  None
21  fractal_dimension2  Feature   Continuous        None        None  None
22             radius3  Feature   Continuous        None        None  None
23            texture3  Feature   Continuous        None        None  None
24          perimeter3  Feature   Continuous        None        None  None
25               area3  Feature   Continuous        None        None  None
26         smoothness3  Feature   Continuous        None        None  None
27        compactness3  Feature   Continuous        None        None  None
28          concavity3  Feature   Continuous        None        None  None
29     concave_points3  Feature   Continuous        None        None  None
30           symmetry3  Feature   Continuous        None        None  None
31  fractal_dimension3  Feature   Continuous        None        None  None

   missing_values
0              no
1              no
2              no
3              no
4              no
5              no
6              no
7              no
8              no
9              no
10             no
11             no
12             no
13             no
14             no
15             no
16             no
17             no
18             no
19             no
20             no
21             no
22             no
23             no
24             no
25             no
26             no
27             no
28             no
29             no
30             no
31             no

In [5]:
print(X.shape, y.shape)

(569, 30) (569, 1)

In [6]:
X.sample(4)

,radius1,texture1,perimeter1,area1,smoothness1,compactness1,concavity1,concave_points1,symmetry1,fractal_dimension1,...,radius3,texture3,perimeter3,area3,smoothness3,compactness3,concavity3,concave_points3,symmetry3,fractal_dimension3
36,14.250,21.72,93.63,633.0,0.09823,0.10980,0.13190,0.05598,0.1885,0.06125,...,15.890,30.36,116.20,799.6,0.1446,0.42380,0.51860,0.14470,0.3591,0.10140
403,12.940,16.17,83.18,507.6,0.09879,0.08836,0.03296,0.02390,0.1735,0.06200,...,13.860,23.02,89.69,580.9,0.1172,0.19580,0.18100,0.08388,0.3297,0.07834
326,14.110,12.88,90.03,616.5,0.09309,0.05306,0.01765,0.02733,0.1373,0.05700,...,15.530,18.00,98.40,749.9,0.1281,0.11090,0.05307,0.05890,0.2100,0.07083
314,8.597,18.60,54.09,221.2,0.10740,0.05847,0.00000,0.00000,0.2163,0.07359,...,8.952,22.44,56.65,240.1,0.1347,0.07767,0.00000,0.00000,0.3142,0.08116

In [7]:
y.sample(4)

    Diagnosis
439         B
399         B
402         B
328         M

In [8]:
y.value_counts()
# Valeur binaire catégorielle B/M

Diagnosis
B            357
M            212
Name: count, dtype: int64

---
## Cross Validation

In [9]:
# Cross-validation demande un array de dimension 1d
y = np.ravel(y)
models = [KNeighborsClassifier(), svm.SVC(), SGDClassifier(), MLPClassifier(max_iter=300)]

for model in models:
    print(f"{model} {cross_val_score(model, X, y, cv = 5 ).mean():.2%}")

KNeighborsClassifier() 92.79%
SVC() 91.22%
SGDClassifier() 89.99%
MLPClassifier(max_iter=300) 92.44%

---
## Grid Search

In [10]:
y = np.ravel(y)
models = [KNeighborsClassifier(), svm.SVC(), SGDClassifier(), MLPClassifier()]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=1)

In [11]:
# Définir les grilles de recherche pour chaque modèle
KNN = {'n_neighbors': [1,2,3,4,5,6,7,8,9,10], # Grille de recherche pour KNeighborsClassifier. On va tester des valeurs de voisins de 3, 5, 7 et 9
        'weights' : ['uniform', 'distance'], 
        'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
        'metric' : ['cityblock', 'euclidean', 'manhattan', 'minkowski']
    }
SVM = {'kernel': ['linear', 'rbf'], # Grille de recherche pour SVC (noyau et paramètre C)
        'C': [0.1, 1, 10, 100], 
        'decision_function_shape': ['ovo', 'ovr']
    }
SGDC =  {'loss': ['hinge', 'log_loss', 'modified_huber', 'squared_hinge', 'perceptron', 'squared_error', 'huber', 'epsilon_insensitive', 'squared_epsilon_insensitive' ], 
         'penalty': ['l2', 'l1', 'elasticnet', None],
         'fit_intercept': [False, True]
    }
MLPC = {'hidden_layer_sizes': [100, 200],
        'activation': ['identity', 'logistic', 'tanh', 'relu'],
        'solver': ['sgd', 'adam'],
        'max_iter' : [1000, 1100, 1200, 1300, 1400, 1500],
    }

param_grids = [KNN, SVM, SGDC, MLPC]

In [12]:
# Création et exécution d'un GridSearchCV pour chaque modèle dans une boucle
# On va parcourir chaque model de la liste de modele et y associer chaque valeur distinct des param_grids
for model, param_grid in zip(models, param_grids):
    start = time.time()
    gs = GridSearchCV(estimator=model, param_grid=param_grid, cv=5)
    gs.fit(X_train, y_train)  # Entraînement du modèle sur les données d'entraînement (X, y)
    end = time.time()
    length = end - start
    # Pour chaque modele on affiche le meilleur score obtenu ainsi que les paramètres qui donnent ce score
    print(f"{length:2f} seconds!") # Afficher le temps de compute de chaque modèle
    print(f"Meilleur score pour {model.__class__.__name__}: {gs.best_score_:.3f}")  # Afficher le meilleur score
    print(f"Meilleurs paramètres pour {model.__class__.__name__}: {gs.best_params_}")  # Afficher les meilleurs paramètres
    print('=================================')

6.923867 seconds!
Meilleur score pour KNeighborsClassifier: 0.938
Meilleurs paramètres pour KNeighborsClassifier: {'algorithm': 'auto', 'metric': 'cityblock', 'n_neighbors': 9, 'weights': 'distance'}
=================================
88.307317 seconds!
Meilleur score pour SVC: 0.949
Meilleurs paramètres pour SVC: {'C': 0.1, 'decision_function_shape': 'ovo', 'kernel': 'linear'}
=================================
2.285417 seconds!
Meilleur score pour SGDClassifier: 0.927
Meilleurs paramètres pour SGDClassifier: {'fit_intercept': True, 'loss': 'modified_huber', 'penalty': 'elasticnet'}
=================================
81.571784 seconds!
Meilleur score pour MLPClassifier: 0.952
Meilleurs paramètres pour MLPClassifier: {'activation': 'logistic', 'hidden_layer_sizes': 100, 'max_iter': 1400, 'solver': 'adam'}
=================================

MLPClassifier obtient le meilleur score, mais c'est un modèle stochastique. 
Le score variera à chaque compute du modèle.

SGDClassifier obtient le moins bon score mais il est clairement le plus rapide